### ISSUE TITLE
player_blind event attacker_steamid is null

### ISSUE THREAD

**Issue by willbex** [LaihoE/demoparser#69] opened 2023-11-13 10:12 UTC
Parsing the player_blind event returns nondeterministic results. Sometimes the attacker_steamid and attacker_name is null and sometimes it's not.

Affected versions: all

Example code:
```
var { parseEvent } = require('@laihoe/demoparser2');

const filePath = process.argv.slice(2)[0];

parsePlayerBlindEvent();

function parsePlayerBlindEvent() {
    let d = parseEvent(filePath, "player_blind")

    d.forEach((e) => {
        if (!e.attacker_steamid) {
            console.log(e);
        }
    });
}
```

Example affected demo file: 
https://drive.google.com/file/d/1UJ_dZaUn7uOr5ezbd6O-XxwtjVoq0Rmd/view?usp=sharing

If you run above code several times you will see nondeterministic results

**Comment by LaihoE** [comment] 2023-11-13 12:56
Hi, thanks for bringing this up. Will be fixed in next patch. Nondeteminism was caused by hashmap iteration + "empty" player slots had userid = 0, an ID that a player could also get.

**Comment by LaihoE** [comment] 2023-11-13 20:20
Could you try with 0.15.0?

**Comment by willbex** [comment] 2023-11-14 09:20
Thanks, it is working now, gj

**Closed** 2023-11-14 09:20 UTC

**Comment by researchersec** [comment] 2023-11-14 22:31
Still reproducing this error on python. Did you not push to pypi yet?

**Comment by LaihoE** [comment] 2023-11-15 10:02
Sometimes it's actually correct to have null as attacker steamid. This is when the damage was caused by something else like the bomb. Is that maybe what you are seeing? Also some old demos might have odd stuff going on.

**Comment by researchersec** [comment] 2023-11-15 17:55
Just getting no values on player_blind events

blinds = parser.parse_events([GameEvent.PLAYER_BLIND.value])
blinds_df = parse_blinds(blinds)

Reproduced with this demo 

https://www.hltv.org/matches/2365256/faze-vs-legends-steelseries-cs2-legends-vs-champions-2023

**Comment by LaihoE** [comment] 2023-11-15 20:11
Game events were missing for some time during the summer. I think exactly around that time. They were re-enabled later on.

**Comment by researchersec** [comment] 2023-11-15 21:25
> Game events were missing for some time during the summer. I think exactly around that time. They were re-enabled later on.

Thanks man!
